version: 2
jobs:
  python27:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: make check
  python36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: make check
  python37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: make check
  python_latest:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: make check
workflows:
  version: 2
  build_and_test:
    jobs:
      - python27
      - python36
      - python37
      - python_latest
